cmd /c ppm install File::Spec::Functions
cmd /c ppm install HTTP::Server::Simple::CGI
cmd /c ppm install CGI::Carp
cmd /c ppm install List::Util
cmd /c ppm install Term::ReadKey
cmd /c ppm install Config::IniHash
cmd /c ppm install Scalar::Util
cmd /c ppm install JSON
cmd /c ppm install File::stat
cmd /c ppm install threads
cmd /c ppm install threads::shared
cmd /c ppm install CGI
cmd /c ppm install List::MoreUtils
cmd /c ppm install Tk
cmd /c ppm install Tk::ROText
cmd /c ppm install Tk::Spinbox
cmd /c ppm install Tk::NoteBook
cmd /c ppm install Tk::Chart::Pie
cmd /c ppm install Tk::Graph
cmd /c ppm install Archive::Zip
cmd /c ppm install FindBin
cmd /c ppm install inc::Module::Install
