cmd /c cpanm File::Spec::Functions
cmd /c cpanm HTTP::Server::Simple::CGI
cmd /c cpanm CGI::Carp
cmd /c cpanm List::Util
cmd /c cpanm Term::ReadKey
cmd /c cpanm Config::IniHash
cmd /c cpanm Scalar::Util
cmd /c cpanm JSON
cmd /c cpanm File::stat
cmd /c cpanm threads
cmd /c cpanm threads::shared
cmd /c cpanm CGI
cmd /c cpanm List::MoreUtils
cmd /c cpanm Tk
cmd /c cpanm Tk::ROText
cmd /c cpanm Tk::Spinbox
cmd /c cpanm Tk::NoteBook
cmd /c cpanm Tk::Chart::Pie
cmd /c cpanm Tk::Graph
cmd /c cpanm Archive::Zip
cmd /c cpanm FindBin
